$:
  vscode:
    - docker:
        # 指定云原生开发启动时的基础镜像为当前镜像
        image: docker.cnb.cool/iiistudio/os/docker/python:3.12.11
      services:
        - vscode
        - docker

main:
  push:
    - services:
        - docker
      imports:
        - https://cnb.cool/IIIStudio/key/-/blob/main/github/env.yml
      stages:
        - name: 同步到GitHub
          image: tencentcom/git-sync 
          settings:
            target_url: https://github.com/IIIStudio/PromptStudio.git
            auth_type: https
            git_user: ${GIT_USERNAME}
            git_email: ${GIT_EMAIL} 
            username: ${GIT_USERNAME} 
            password: ${GIT_ACCESS_TOKEN}
            branch: main
            sync_mode: mirror  # 镜像模式，直接覆盖
            force: true
  web_trigger:
    - runner:
        cpus: 1
      stages:
        - name: 测回
          script: |
            git reset --hard ${commit}
            git push -f origin main