$:
  vscode:
    - docker:
        # 指定云原生开发启动时的基础镜像为当前镜像
        image: docker.cnb.cool/ohao/learn/python:3.12.11
      services:
        - vscode
        - docker

main:
  push:
    - stages:
      - name: tcloud-cmd
        imports: https://cnb.cool/IIIStudio/key/-/blob/main/Lighthouse/env.yml
        image: tencentcom/tcloud-cmd
        settings:
          secret_id: ${SECRET_ID}
          secret_key: ${SECRET_KEY}
          region: ${region}
          instance_ids: ${instance_ids}
          script: ${script}